create table
  public.files (
    id serial,
    user_id uuid null,
    file_name text not null,
    file_type text null,
    file_size bigint null,
    upload_date timestamp with time zone null default now(),
    uuid uuid null,
    status text not null,
    url text null,
    constraint files_pkey primary key (id),
    constraint files_user_id_fkey foreign key (user_id) references auth.users (id),
    constraint files_uuid_fkey foreign key (uuid) references auth.users (id) on update cascade
  ) tablespace pg_default;

create view
  public.objects as
select
  objects.name,
  objects.created_at
from
  storage.objects;

create table
  public.user_keys (
    id bigint generated by default as identity,
    pinecone_key text null,
    pinecone_env text null,
    index_name text null,
    openai_key text null,
    user_id uuid null,
    user_email character varying null,
    constraint user_keys_pkey primary key (id),
    constraint user_keys_user_id_fkey foreign key (user_id) references auth.users (id) on update cascade
  ) tablespace pg_default;