OPENAPI_KEY = <ENTER OPENAPI KEY HERE>
PINECONE_API_KEY = <ENTER PINECONE API KEY HERE>
PINECONE_ENVIRONMENT = <ENTER PINECONE ENVIRONMENT HERE>
PINECONE_INDEX_NAME = <ENTER PINECONE INDEX NAME HERE>
